salab/src/main/webapp/WEB-INF/views/main.jsp, salab/src/main/webapp/resources/js/main.js
=> 191031 19:29

salab/src/main/webapp/WEB-INF/views/userPage/userPageMain.jsp
=> userPageMain파일생성

salab/src/main/webapp/WEB-INF/views/userPage/userChangePwd.jsp, salab/src/main/webapp/WEB-INF/views/userPage/userPageMain.jsp, salab/src/main/webapp/WEB-INF/views/userPage/userUpgrade.jsp, salab/src/main/webapp/resources/css/userPage/userPageCommon.css, salab/src/main/webapp/resources/css/userPage/userPageMain.css
191103 15:45 userPage 파일s 생성 및 기본 틀 작성
=> 191103 15:45 userPage 파일s 생성 및 기본 틀 작성

salab/src/main/java/com/sesame/salab/member/controller/MemberController.java, salab/src/main/java/com/sesame/salab/privatefile/controller/PrivateFileController.java, salab/src/main/java/com/sesame/salab/privatefile/model/dao/PrivateFileDao.java, salab/src/main/java/com/sesame/salab/privatefile/model/service/PrivateFileService.java, salab/src/main/java/com/sesame/salab/privatefile/model/service/PrivateFileServiceImpl.java, salab/src/main/java/com/sesame/salab/privatefile/model/vo/PrivateFile.java, salab/src/main/resources/mappers/privatefile-mapper.xml, salab/src/main/resources/mybatis-config.xml, salab/src/main/webapp/WEB-INF/views/editPrivateFile/editPrivateFile.jsp, salab/src/main/webapp/WEB-INF/views/recentFile/recentFile.jsp, salab/src/main/webapp/resources/js/editPrivateFile/dragndrop.js, salab/target/classes/mappers/privatefile-mapper.xml, salab/target/classes/mybatis-config.xml
memberController에 login,do에 코드추가했고 privatefile mvc패턴으로 생성
=> 20191107 12:02 새파일 생성 완료

salab/src/main/webapp/WEB-INF/views/editPrivateFile/editPrivateFile.jsp, salab/src/main/webapp/resources/css/editPrivateFile/components.css, salab/src/main/webapp/resources/js/editPrivateFile/componentList.js, salab/src/main/webapp/resources/js/editPrivateFile/dragndrop.js
**현재 발생하는 이슈**
1. Object 일부 밀림 현상
- heading / paragraph
2. MultiDrag 구현
3. Multi Resize 할 거냐?(살려줘)
+ component 지우는거 추가해놈
=> 191110 23:26 dragndrop almost done

salab/src/main/webapp/resources/js/editPrivateFile/dragndrop.js, salab/src/main/webapp/resources/js/editPrivateFile/rightSidebar.js
=> 2019 11 14 이승진 commit

salab/src/main/java/com/sesame/salab/common/PageController.java, salab/src/main/webapp/WEB-INF/views/editPrivateFile/editPrivateFile.jsp, salab/src/main/webapp/WEB-INF/views/textTest.jsp, salab/src/main/webapp/resources/css/editPrivateFile/editFile.css, salab/src/main/webapp/resources/js/editPrivateFile/rightSidebar.js
=> 2019 11 19 이승진 commit

salab/src/main/java/com/sesame/salab/member/model/vo/Member.java, salab/src/main/java/com/sesame/salab/payment/controller/PaymentController.java, salab/src/main/java/com/sesame/salab/payment/dao/PaymentDao.java, salab/src/main/java/com/sesame/salab/payment/service/PaymentService.java, salab/src/main/java/com/sesame/salab/payment/service/PaymentServiceImpl.java, salab/src/main/resources/mappers/payment-mapper.xml, salab/src/main/webapp/WEB-INF/views/test.jsp, salab/src/main/webapp/WEB-INF/views/userPage/userUpgrade.jsp, salab/target/classes/mappers/member-mapper.xml, salab/target/classes/mappers/member_project-mapper.xml
19.11.19 12:18 마이페이지 결제기능. 정기결제 구현
=> 19.11.19 12:18 마이페이지 결제기능. 정기결제 구현

salab/src/main/java/com/sesame/salab/common/TaskScheduler.java, salab/src/main/java/com/sesame/salab/userPage/controller/UserController.java, salab/src/main/java/com/sesame/salab/userPage/model/dao/userPageDao.java, salab/src/main/java/com/sesame/salab/userPage/model/service/userPageService.java, salab/src/main/java/com/sesame/salab/userPage/model/service/userPageServiceImpl.java, salab/src/main/resources/mappers/userPage-mapper.xml, salab/src/main/webapp/WEB-INF/views/userPage/userPageMain.jsp, salab/src/main/webapp/resources/css/userPage/userPageMain.css, salab/src/main/webapp/vendors/css/croppie.css, salab/src/main/webapp/vendors/js/croppie.js
=> 19.11.21 13:20 유저 파일업로드기능 구현

salab/src/main/webapp/resources/js/editPrivateFile/dragndrop.js, salab/src/main/webapp/resources/js/editPrivateFile/page.js
custom sizing 만하면됨
+
zoom 조절
canvas 사이즈 위치 조절
=> 191127 11:06 canvas(2.5/3)

salab/src/main/webapp/WEB-INF/views/editPrivateFile/editPrivateFile.jsp, salab/src/main/webapp/resources/css/editPrivateFile/editFile.css, salab/src/main/webapp/resources/js/editPrivateFile/dragndrop.js, salab/src/main/webapp/resources/js/editPrivateFile/rightSidebar.js
=> 2019-11-27 이승진 commit

salab/src/main/java/com/sesame/salab/common/PageController.java, salab/src/main/java/com/sesame/salab/common/paging/model/vo/Paging.java, salab/src/main/java/com/sesame/salab/projectnotice/controller/projectnoticeController.java, salab/src/main/java/com/sesame/salab/projectnotice/model/dao/projectnoticeDao.java, salab/src/main/java/com/sesame/salab/projectnotice/model/service/ProjectnoticeImpl.java, salab/src/main/java/com/sesame/salab/projectnotice/model/service/ProjectnoticeService.java, salab/src/main/resources/mappers/projectnotice-mapper.xml, salab/src/main/webapp/WEB-INF/views/project/teamNoticeDetail.jsp, salab/src/main/webapp/WEB-INF/views/project/teamNoticeList.jsp, salab/src/main/webapp/WEB-INF/views/project/teamNoticeWrite.jsp, salab/src/main/webapp/resources/css/project/teamNoticeList.css, salab/src/main/webapp/resources/js/project/teamNoticeList.js
19.11.28 12:14 project-notice 기능구현
=> 19.11.28 12:14 project-notice 기능구현

salab/src/main/java/com/sesame/salab/project/controller/ProjectController.java, salab/src/main/java/com/sesame/salab/project/model/dao/ProjectDao.java, salab/src/main/java/com/sesame/salab/project/model/service/ProjectService.java, salab/src/main/java/com/sesame/salab/project/model/service/ProjectServiceImpl.java, salab/src/main/java/com/sesame/salab/project/model/vo/ProjectMember.java, salab/src/main/java/com/sesame/salab/projectnotice/controller/projectnoticeController.java, salab/src/main/java/com/sesame/salab/projectnotice/model/dao/projectnoticeDao.java, salab/src/main/java/com/sesame/salab/projectnotice/model/service/ProjectnoticeImpl.java, salab/src/main/java/com/sesame/salab/projectnotice/model/service/ProjectnoticeService.java, salab/src/main/resources/mappers/project-mapper.xml, salab/src/main/webapp/WEB-INF/views/project/projectMainPage.jsp, salab/src/main/webapp/resources/css/project/projectMainPage.css, salab/src/main/webapp/resources/js/project/teamNoticeList.js
19.11.29 15:15  project main 공지사항, 팀멤버 데이터로딩 구현.
=> 19.11.29 15:15  project main 공지사항, 팀멤버 데이터로딩 구현.

salab/src/main/java/com/sesame/salab/project/model/vo/ProjectMember.java, salab/src/main/resources/mybatis-config.xml
19.12.01. 12:52 mybatis에 ProjectMember 누락된 부분 추가커밋.
=> Parkgeonwoo

salab/src/main/webapp/resources/css/editPrivateFile/components.css, salab/src/main/webapp/resources/css/editPrivateFile/editFile.css, salab/src/main/webapp/resources/js/editPrivateFile/componentList.js, salab/src/main/webapp/resources/js/editPrivateFile/dragndrop.js, salab/src/main/webapp/resources/js/editPrivateFile/rightSidebar.js, salab/src/main/webapp/resources/js/editPrivateFile/shortcut.js
=> 2019 12 01 이승진 commit

salab/src/main/java/com/sesame/salab/HomeController.java, salab/src/main/java/com/sesame/salab/common/FileList.java, salab/src/main/java/com/sesame/salab/common/PageController.java, salab/src/main/java/com/sesame/salab/member/controller/MemberController.java, salab/src/main/java/com/sesame/salab/privatefile/model/dao/PrivateFileDao.java, salab/src/main/java/com/sesame/salab/privatefile/model/service/PrivateFileService.java, salab/src/main/java/com/sesame/salab/privatefile/model/service/PrivateFileServiceImpl.java, salab/src/main/resources/mappers/privatefile-mapper.xml, salab/src/main/resources/mybatis-config.xml, salab/src/main/webapp/WEB-INF/views/recentFile/recentFile.jsp, salab/src/main/webapp/resources/css/recentFile/recentFile.css, salab/src/main/webapp/resources/js/recentFile/recentFile.js
변경사항
1. recentfile.jsp에 문제가 되는 thumbnail 주석처리함
2. pagecontroller에서 setPfthumbnail이 문제 발생하여 주석처리함
=> 191201 21:00 파일 목록 조회

salab/src/main/java/com/sesame/salab/project/controller/ProjectController.java, salab/src/main/java/com/sesame/salab/project/model/dao/ProjectDao.java, salab/src/main/java/com/sesame/salab/project/model/service/ProjectService.java, salab/src/main/java/com/sesame/salab/project/model/service/ProjectServiceImpl.java, salab/src/main/java/com/sesame/salab/projectnotice/controller/projectnoticeController.java, salab/src/main/resources/mappers/member_project-mapper.xml, salab/src/main/resources/mappers/project-mapper.xml, salab/src/main/webapp/WEB-INF/views/project/projectMainPage.jsp, salab/src/main/webapp/WEB-INF/views/project/teamNoticeDetail.jsp, salab/src/main/webapp/WEB-INF/views/project/teamNoticeList.jsp, salab/src/main/webapp/resources/js/project/projectMain.js, salab/src/main/webapp/resources/js/project/teamNoticeList.js
19.12.02 09:11 공지사항기능 완성, 멤버 권한변경,강퇴기능구현
=> 19.12.02 09:11 공지사항기능 완성, 멤버 권한변경,강퇴기능구현

salab/src/main/webapp/resources/css/project/projectMainPage.css, salab/src/main/webapp/resources/js/project/projectMain.js
=> 19.12.02 09:18 자잘한 error해결

salab/src/main/java/com/sesame/salab/common/PageController.java, salab/src/main/webapp/WEB-INF/views/editPrivateFile/editPrivateFile.jsp, salab/src/main/webapp/WEB-INF/views/testText.jsp, salab/src/main/webapp/resources/js/editPrivateFile/dragndrop.js, salab/src/main/webapp/resources/js/editPrivateFile/rightSidebar.js
=> 2019-12-03 이승진 commit

salab/src/main/webapp/WEB-INF/views/editPrivateFile/editPrivateFile.jsp, salab/src/main/webapp/resources/css/editPrivateFile/components.css, salab/src/main/webapp/resources/js/editPrivateFile/dragndrop.js, salab/src/main/webapp/resources/js/editPrivateFile/rightSidebar.js, salab/target/classes/mappers/.gitignore
=> 2019 12 04 이승진 commit

salab/src/main/webapp/resources/js/editPrivateFile/dragndrop.js, salab/src/main/webapp/resources/js/editPrivateFile/rightSidebar.js
=> 2019-12-04 이승진 commit

salab/src/main/webapp/WEB-INF/views/project/projectMainPage.jsp
19.12.05 2:20 merge 위한 중간 commit
=> 19.12.05 2:20 merge 위한 중간 commit

salab/src/main/java/com/sesame/salab/project/controller/ProjectController.java, salab/src/main/java/com/sesame/salab/project/model/dao/ProjectDao.java, salab/src/main/java/com/sesame/salab/project/model/service/ProjectService.java, salab/src/main/java/com/sesame/salab/project/model/service/ProjectServiceImpl.java, salab/src/main/resources/mappers/project-mapper.xml, salab/src/main/webapp/WEB-INF/views/project/projectMainPage.jsp, salab/src/main/webapp/resources/css/project/projectMainPage.css
19.12.05 09:49 프로젝트 이미지 저장구현. (default img 찾는중)
=> 19.12.05 09:49 프로젝트 이미지 저장구현. (default img 찾는중)

salab/src/main/java/com/sesame/salab/project/controller/ProjectController.java, salab/src/main/java/com/sesame/salab/project/model/dao/ProjectDao.java, salab/src/main/resources/mappers/ProjectFile-mapper.xml, salab/src/main/webapp/WEB-INF/views/project/projectMainPage.jsp, salab/src/main/webapp/WEB-INF/views/project/teamNoticeWrite.jsp, salab/src/main/webapp/resources/css/project/projectMainPage.css, salab/src/main/webapp/resources/css/recentFile/recentFile.css, salab/src/main/webapp/resources/js/project/projectMain.js
19.12.05 15:05 프로젝트페이지 resizing, 프로젝트 이미지 존재할 시 표시하기.
=> 19.12.05 15:05 프로젝트페이지 resizing, 프로젝트 이미지 존재할 시 표시하기.

salab/src/main/webapp/WEB-INF/views/userPage/userPageMain.jsp, salab/src/main/webapp/resources/css/userPage/userPageMain.css, salab/src/main/webapp/resources/js/userPage/userPageMain.js
19.12.07 23:52 userPage 고객등급별 표시내용 수정, 번호변경추가. 유효성검사 코드 변경
=> 19.12.07 23:52 userPage 번호변경 기능추가. 유효성검사 코드 변경

salab/src/main/webapp/resources/css/project/projectMainPage.css, salab/src/main/webapp/resources/css/userPage/userPageMain.css
=> 19.12.08 12:24 누락본추가

salab/src/main/webapp/WEB-INF/views/project/projectFile.jsp, salab/src/main/webapp/WEB-INF/views/userPage/userPageMain.jsp, salab/src/main/webapp/WEB-INF/views/userPage/userUpgrade.jsp, salab/src/main/webapp/resources/css/userPage/userPageMain.css, salab/src/main/webapp/resources/css/userPage/userUpgrade.css, salab/src/main/webapp/resources/js/userPage/userPageMain.js
=> 19.12.08 15:35 유저페이지 상단 수정

salab/src/main/java/com/sesame/salab/project/controller/ProjectController.java, salab/src/main/webapp/WEB-INF/views/privateFile/privateFile.jsp, salab/src/main/webapp/WEB-INF/views/project/projectFile.jsp, salab/src/main/webapp/WEB-INF/views/project/projectMainPage.jsp, salab/src/main/webapp/WEB-INF/views/project/teamNoticeDetail.jsp, salab/src/main/webapp/WEB-INF/views/project/teamNoticeList.jsp, salab/src/main/webapp/WEB-INF/views/project/teamNoticeWrite.jsp, salab/src/main/webapp/WEB-INF/views/recentFile/recentFile.jsp, salab/src/main/webapp/WEB-INF/views/trashCan/trashCan.jsp, salab/src/main/webapp/WEB-INF/views/userPage/userPageMain.jsp, salab/src/main/webapp/WEB-INF/views/userPage/userUpgrade.jsp, salab/src/main/webapp/resources/css/common.css, salab/src/main/webapp/resources/css/project/projectMainPage.css, salab/src/main/webapp/resources/css/userPage/userUpgrade.css, salab/src/main/webapp/resources/js/project/projectMain.js, salab/src/main/webapp/resources/js/project/teamNoticeList.js, salab/src/main/webapp/resources/js/recentFile/recentFile.js
1. 프로젝트파일,개인페이지에서 + 버튼 없에기, 메인페이지에서 +버튼 파일생성  연결하기
2. Userimg 변경시, 사진 뜨게.
3. 고객센터로 연결하기
4. 상단 a태그 활성화하기
5. 팀 공지사항에서 좌측 리스트에 active클래스 수정
6. 프로젝트페이지 etFile.do 연결하기_파일생성시 개인파일로 연결
7. 사진변경에서 화질 올리기
=> 19.12.10 04:11 To do리스트 작업사항 커밋

salab/src/main/java/com/sesame/salab/project/controller/ProjectController.java, salab/src/main/java/com/sesame/salab/projectnotice/controller/projectnoticeController.java, salab/src/main/webapp/WEB-INF/views/project/projectMainPage.jsp, salab/src/main/webapp/WEB-INF/views/project/teamNoticeList.jsp, salab/src/main/webapp/WEB-INF/views/userPage/userPageMain.jsp, salab/src/main/webapp/WEB-INF/views/userPage/userUpgrade.jsp, salab/src/main/webapp/resources/css/project/projectMainPage.css, salab/src/main/webapp/resources/css/project/teamNoticeDetail.css, salab/src/main/webapp/resources/css/project/teamNoticeList.css, salab/src/main/webapp/resources/css/recentFile/recentFile.css, salab/src/main/webapp/resources/css/userPage/Upgrade.css, salab/src/main/webapp/resources/css/userPage/userPageCommon.css, salab/src/main/webapp/resources/css/userPage/userPageMain.css, salab/src/main/webapp/resources/css/userPage/userUpgrade.css
=> 19.12.10 19:00 중간커밋

salab/src/main/java/com/sesame/salab/common/PageController.java, salab/src/main/java/com/sesame/salab/member/controller/MemberController.java, salab/src/main/java/com/sesame/salab/member/model/dao/MemberDao.java, salab/src/main/java/com/sesame/salab/member/model/service/MemberService.java, salab/src/main/java/com/sesame/salab/member/model/service/MemberServiceImpl.java, salab/src/main/java/com/sesame/salab/payment/controller/PaymentController.java, salab/src/main/java/com/sesame/salab/payment/model/vo/Scheduling.java, salab/src/main/resources/mappers/member-mapper.xml, salab/src/main/webapp/WEB-INF/views/userPage/userPageMain.jsp, salab/src/main/webapp/WEB-INF/views/userPage/userUpgrade.jsp
19.12.11 16:00 정기결제기능 완료,premium 정기결제 해제 기능,  premium 만료회원 처리 method추가.
=> 19.12.11 16:00 정기결제기능 완료,premium 정기결제 해제 기능,  premium 만료회원 처리 method추가.

salab/src/main/webapp/WEB-INF/views/editPrivateFile/editPrivateFile.jsp, salab/src/main/webapp/resources/css/editPrivateFile/components.css, salab/src/main/webapp/resources/js/editPrivateFile/componentList.js
=> 19.12.18 15:13 dropdown 컴포넌트

salab/src/main/java/com/sesame/salab/project/controller/ProjectController.java, salab/src/main/webapp/WEB-INF/views/editPrivateFile/editPrivateFile.jsp, salab/src/main/webapp/WEB-INF/views/project/investTeam.jsp, salab/src/main/webapp/WEB-INF/views/project/newTeam.jsp, salab/src/main/webapp/resources/css/editPrivateFile/components.css, salab/src/main/webapp/resources/css/project/createProject.css, salab/src/main/webapp/resources/js/editPrivateFile/componentList.js
19.12.19 06:00 프로젝트생성-팀원초대 잔오류해결, tab-content 정리중,
=> 19.12.19 06:00 프로젝트생성-팀원초대 잔오류해결, tab-content 정리중,

salab/src/main/java/com/sesame/salab/payment/model/vo/Scheduling.java, salab/src/main/webapp/WEB-INF/views/editPrivateFile/editPrivateFile.jsp, salab/src/main/webapp/WEB-INF/views/project/projectMainPage.jsp, salab/src/main/webapp/WEB-INF/views/project/teamNoticeList.jsp, salab/src/main/webapp/WEB-INF/views/project/teamNoticeWrite.jsp, salab/src/main/webapp/WEB-INF/views/userPage/userUpgrade.jsp, salab/src/main/webapp/resources/css/editPrivateFile/components.css, salab/src/main/webapp/resources/css/editPrivateFile/editFile.css, salab/src/main/webapp/resources/css/project/projectMainPage.css, salab/src/main/webapp/resources/css/project/teamNoticeList.css, salab/src/main/webapp/resources/css/userPage/userPageCommon.css, salab/src/main/webapp/resources/js/editPrivateFile/componentList.js, salab/src/main/webapp/resources/js/editPrivateFile/page.js, salab/src/main/webapp/resources/js/userPage/userPageMain.js, salab/target/classes/mappers/project-mapper.xml
19.12.22 1:02 오브젝트5종 추가, 가운데정렬,  프로젝트에 유저이미지, 기타 오류 수정
=> 19.12.22 1:02 오브젝트5종 추가, 가운데정렬,  프로젝트에 유저이미지, 기타 오류 수정

salab/src/main/webapp/WEB-INF/views/editTeamFile/editTeamFile.jsp, salab/src/main/webapp/resources/css/editTeamFile/teamComponents.css, salab/src/main/webapp/resources/js/editTeamFile/componentList.js, salab/src/main/webapp/resources/svg/diagonal_L.svg, salab/src/main/webapp/resources/svg/diagonal_R.svg, salab/src/main/webapp/resources/svg/line-horizontal.svg, salab/src/main/webapp/resources/svg/line-vertical.svg, salab/src/main/webapp/resources/svg/wireframe.svg
19.12.23 09:53 privatefile 을 projectFile 로 복사
=> 19.12.23 09:53 privatefile 을 projectFile 로 복사

salab/src/main/java/com/sesame/salab/member/controller/MemberController.java, salab/src/main/webapp/WEB-INF/views/admin/adminMemberDetail.jsp, salab/src/main/webapp/resources/js/project/projectMain.js
19.12.23 14:17 프로젝트 팀원 초대에서 모달창 꺼지는것수정.
=> 19.12.23 14:17 프로젝트 팀원 초대에서 모달창 꺼지는것수정.
